Laboratorium 3 - App/Models/Software.cs
namespace Laboratorium_3___App.Models
{
    public class Software
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
    }
}

Laboratorium 3 - App/Controllers/SoftwareController.cs
using Laboratorium_3___App.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_3___App.Controllers
{
    public class SoftwareController : Controller
    {
        private readonly ISoftwareService _softwareService;
        public SoftwareController(ISoftwareService softwareService)
        {
            _softwareService = softwareService;
        }
      
        public ActionResult Index()
        {
            return View(_softwareService.FindAll());
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(_softwareService.FindById(id));
        }
        [HttpPost]
        public IActionResult Details(Computer model)
        {
            return RedirectToAction("Index");
        }

  

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
       
        public ActionResult Create(Software model)
        {
            if (ModelState.IsValid)
            {
                _softwareService.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            return View(_softwareService.FindById(id));
        }

       
        [HttpPost]
        
        public ActionResult Update(Software model)
        {
            if (ModelState.IsValid)
            {
                _softwareService.Update(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Software software = _softwareService.FindById(id);
            if (software == null)
            {
                return NotFound();
            }
            return View(software);
        }

        
        [HttpPost]
       
        public ActionResult Delete(Software model)
        {
            _softwareService.Delete(model.Id);
            return RedirectToAction("Index");
        }
    }
}

Laboratorium 3 - App/Views/Software/Create.cshtml
@model Software
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Dodaj Oprogramowanie</h2>
<form asp-controller="Software" asp-action="Create" method="post">

    <div class="mb-4">
        <label asp-for="Name">Nazwa</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-4">
        <label asp-for="Version">Wersja</label>
        <input class="form-control" asp-for="Version" />
        <span class="text-danger" asp-validation-for="Version"></span>

  


    <div class="mb-4">
        <button class=" btn btn-primary" type="submit">Dodaj</button>
    </div>

</form>

Laboratorium 3 - App/Views/Software/Index.cshtml
@model List<Software>

<h2>Lista Oprogramowań</h2>

<a class="btn btn-primary" asp-controller="Software" asp-action="Create">Dodaj oprogramowanie</a>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nazwa</th>
            <th>Wersja</th>
            <th>Akcje</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var software in Model)
        {
            <tr>
                <td>@software.Id</td>
                <td>@software.Name</td>
                <td>@software.Version</td>

                <td>
                    <a asp-action="Details" asp-route-id="@software.Id">Szczegóły</a> |
                    <a asp-action="Update" asp-route-id="@software.Id">Edytuj</a> |
                    <a asp-action="Delete" asp-route-id="@software.Id">Usuń</a>
                </td>
            </tr>
        }
    </tbody>
</table>